"""The three tables that turn a code into something you can read.

An aircraft broadcasts `DLH6CH`, `A20N` and `484123`, never "Lufthansa",
never "Airbus A320neo" and never "the Netherlands". Those names are not in
aircraft.json and cannot be: they are what someone wrote down once, and the
only way to have them is to have the list. So the lists ship with the
integration, generated by `scripts/build_reference.py` out of public domain
data, and are read off disk rather than off the internet. That keeps this on
the right side of the line the [route lookup](route.py) is on the other side
of: a route changes daily and has to be asked for, an airline's name does not.

All three are read once per Home Assistant, not once per station, because
several entries commonly sit in front of the same decoder.
"""

from __future__ import annotations

from bisect import bisect_right
from dataclasses import dataclass, field
import json
import logging
from pathlib import Path
from typing import Any, Final

from homeassistant.core import HomeAssistant

from .const import (
    WATCHLIST_HEX,
    WATCHLIST_NAME,
    WATCHLIST_SQUAWK,
    WATCHLIST_TYPE,
)

_LOGGER = logging.getLogger(__name__)

_DIRECTORY: Final = Path(__file__).parent
AIRLINES_FILE: Final = "airlines.json"
MODELS_FILE: Final = "aircraft_models.json"
CODE_BLOCKS_FILE: Final = "code_blocks.json"

# The length of an ICAO airline designator, which is what a callsign opens with.
_DESIGNATOR_LENGTH: Final = 3

# The length of the address every aircraft transmits, written in hexadecimal,
# of the squawk it is assigned, and what a name can be between. Five is a
# Dutch PH-BXA without its dash; ten leaves room for the longest scheme in
# use and for a callsign with a long flight number behind it.
_ADDRESS_LENGTH: Final = 6
_HEX_CHARACTERS: Final = frozenset("0123456789ABCDEF")
_SQUAWK_LENGTH: Final = 4
_NAME_LENGTH: Final = (3, 10)


@dataclass(frozen=True, kw_only=True)
class ReferenceTables:
    """The airline designators, the aircraft type codes and the address blocks."""

    airlines: dict[str, str] = field(default_factory=dict)
    models: dict[str, str] = field(default_factory=dict)
    # The address blocks as two sequences rather than one, because a lookup is
    # a binary search over the starts and nothing else: the answer is read out
    # of the second at the index the first found.
    starts: tuple[int, ...] = ()
    blocks: tuple[tuple[int, str, bool], ...] = ()

    def airline_of(self, callsign: str | None) -> str | None:
        """Return the airline a callsign belongs to, if this table knows it."""
        designator = designator_of(callsign)
        return None if designator is None else self.airlines.get(designator)

    def model_of(self, type_code: str | None) -> str | None:
        """Return what an ICAO type code stands for, as far as we know it."""
        if type_code is None:
            return None
        return self.models.get(type_code.strip().upper())

    def _block_of(self, hex_code: str | None) -> tuple[int, str, bool] | None:
        """Return the address block a hex code falls in, if it falls in one.

        The blocks do not cover the whole address space and are not meant to.
        Ranges nobody was given are left out, as are the ones that belong to
        no single state, and readsb prefixes an address it worked out rather
        than heard with a `~`, which is not an ICAO address at all. All three
        arrive here and all three land outside every block.
        """
        if not self.starts or hex_code is None:
            return None
        try:
            address = int(hex_code.strip(), 16)
        except ValueError:
            return None
        index = bisect_right(self.starts, address) - 1
        if index < 0:
            return None
        block = self.blocks[index]
        return None if address > block[0] else block

    def country_of(self, hex_code: str | None) -> str | None:
        """Return the ISO country code an aircraft's address was handed to."""
        block = self._block_of(hex_code)
        return None if block is None else block[1]

    def is_military(self, hex_code: str | None) -> bool:
        """Return whether an address sits in a range a state keeps for itself.

        Coarser than the military flag a decoder with an aircraft database
        sends, which knows the individual tail: this only knows that the
        country put the range aside, and a civil aircraft inside one exists.
        It is the answer for the stations that have no database at all.
        """
        block = self._block_of(hex_code)
        return block is not None and block[2]


def designator_of(callsign: str | None) -> str | None:
    """Return the airline designator a callsign opens with, if it is one.

    A flight number is an airline designator followed by the number of the
    flight, as in KLM1234. Anything else that reaches us here is not one: a
    business jet and most general aviation fly under their registration, and
    the military under a name of its own. Reading the first three letters of
    those would turn PHABC into whatever PHA happens to be, so a callsign that
    is not shaped like a flight number has no designator to give.

    The table is not consulted, deliberately. This is what the aircraft itself
    broadcast, and an airline the table has never heard of still has a code
    worth passing on: it is what a dashboard looks a logo up by.
    """
    if callsign is None:
        return None
    text = callsign.strip().upper()
    if len(text) <= _DESIGNATOR_LENGTH:
        return None
    designator, rest = text[:_DESIGNATOR_LENGTH], text[_DESIGNATOR_LENGTH:]
    if not (designator.isascii() and designator.isalpha() and rest[0].isdigit()):
        return None
    return designator


def normalise(text: str | None) -> str:
    """Return an identifier as it is compared: capitals, no dashes, no space.

    A registration is written `PH-BXA` in one place and `PHBXA` in another,
    and an aircraft broadcasts whichever its database was given. Comparing
    them any other way makes a watchlist entry that silently never matches.
    """
    if text is None:
        return ""
    return "".join(character for character in text.upper() if character.isalnum())


def kind_of(entry: str, models: dict[str, str]) -> str | None:
    """Return what a line on a watchlist is, or None if it is nothing.

    The shape says which it is, the same way a callsign's shape says whether
    it opens with an airline designator. Nothing here is guessed: a line that
    fits none of the four is refused rather than read as the likeliest one,
    because a watchlist that quietly never matches is worse than one that
    would not save.
    """
    text = normalise(entry)
    if not text:
        return None
    if len(text) == _SQUAWK_LENGTH and text.isdigit():
        return WATCHLIST_SQUAWK
    if len(text) == _ADDRESS_LENGTH and all(
        character in _HEX_CHARACTERS for character in text
    ):
        return WATCHLIST_HEX
    if text in models:
        return WATCHLIST_TYPE
    # Everything else that carries a letter is a name the aircraft flies
    # under. Which of the two it is cannot be told apart and does not need
    # to be: PH-BXA is a registration, KLM123 a callsign, and N123AB could
    # be read as either, so it is compared against both and the match says
    # which one it hit.
    if (
        _NAME_LENGTH[0] <= len(text) <= _NAME_LENGTH[1]
        and any(character.isalpha() for character in text)
    ):
        return WATCHLIST_NAME
    return None


EMPTY: Final = ReferenceTables()

_tables: ReferenceTables | None = None


def _read(filename: str, key: str) -> dict[str, str]:
    """Read one generated table, tolerating a file that is not there."""
    try:
        payload: Any = json.loads((_DIRECTORY / filename).read_text("utf-8"))
        table = payload[key]
    except (OSError, ValueError, KeyError, TypeError) as err:
        # Nothing here is worth failing a setup over. Without the table the
        # aircraft keep every figure they had; they lose a name.
        _LOGGER.warning("Could not read %s: %s", filename, err)
        return {}
    if not isinstance(table, dict):
        _LOGGER.warning("%s does not hold a table of %s", filename, key)
        return {}
    return {str(code): str(name) for code, name in table.items()}


def _read_blocks(
    filename: str = CODE_BLOCKS_FILE,
) -> tuple[tuple[int, ...], tuple[tuple[int, str, bool], ...]]:
    """Read the address blocks, tolerating a file that is not there.

    Same as `_read` in what it is willing to lose, and separate from it
    because what it reads is not a table of names: the keys are numbers
    written in hexadecimal, and the values carry three things.
    """
    try:
        payload: Any = json.loads((_DIRECTORY / filename).read_text("utf-8"))
        table = payload["blocks"]
    except (OSError, ValueError, KeyError, TypeError) as err:
        # As with the other two, an aircraft without this keeps every figure
        # it had; it loses a country, and its military marker falls back to
        # whatever the decoder said.
        _LOGGER.warning("Could not read %s: %s", filename, err)
        return (), ()
    if not isinstance(table, dict):
        _LOGGER.warning("%s does not hold a table of blocks", filename)
        return (), ()

    blocks: list[tuple[int, int, str, bool]] = []
    for start, value in table.items():
        try:
            finish, country, military = value
            blocks.append(
                (int(start, 16), int(finish, 16), str(country), bool(military))
            )
        except (ValueError, TypeError):
            _LOGGER.warning("Skipping block %s of %s", start, filename)
    blocks.sort()
    return tuple(block[0] for block in blocks), tuple(block[1:] for block in blocks)


def _load() -> ReferenceTables:
    """Read all three tables. Blocking, so this belongs in the executor."""
    starts, blocks = _read_blocks()
    return ReferenceTables(
        airlines=_read(AIRLINES_FILE, "airlines"),
        models=_read(MODELS_FILE, "models"),
        starts=starts,
        blocks=blocks,
    )


async def async_load_reference(hass: HomeAssistant) -> ReferenceTables:
    """Return the tables, reading them off disk the first time they are asked for."""
    global _tables
    if _tables is None:
        _tables = await hass.async_add_executor_job(_load)
        _LOGGER.debug(
            "Loaded %s airlines, %s aircraft types and %s address blocks",
            len(_tables.airlines),
            len(_tables.models),
            len(_tables.starts),
        )
    return _tables
