"""The two tables that turn a code into a name.

An aircraft broadcasts `DLH6CH` and `A20N`, never "Lufthansa" and never
"Airbus A320neo". Those names are not in aircraft.json and cannot be: they are
what someone wrote down once, and the only way to have them is to have the
list. So the list ships with the integration, generated by
`scripts/build_reference.py` out of public domain data, and is read off disk
rather than off the internet. That keeps this on the right side of the line
the [route lookup](route.py) is on the other side of: a route changes daily
and has to be asked for, an airline's name does not.

Both tables are read once per Home Assistant, not once per station, because
several entries commonly sit in front of the same decoder.
"""

from __future__ import annotations

from dataclasses import dataclass, field
import json
import logging
from pathlib import Path
from typing import Any, Final

from homeassistant.core import HomeAssistant

_LOGGER = logging.getLogger(__name__)

_DIRECTORY: Final = Path(__file__).parent
AIRLINES_FILE: Final = "airlines.json"
MODELS_FILE: Final = "aircraft_models.json"

# The length of an ICAO airline designator, which is what a callsign opens with.
_DESIGNATOR_LENGTH: Final = 3


@dataclass(frozen=True, kw_only=True)
class ReferenceTables:
    """The airline designators and the aircraft type codes, by code."""

    airlines: dict[str, str] = field(default_factory=dict)
    models: dict[str, str] = field(default_factory=dict)

    def airline_of(self, callsign: str | None) -> str | None:
        """Return the airline a callsign belongs to, if this table knows it."""
        designator = designator_of(callsign)
        return None if designator is None else self.airlines.get(designator)

    def model_of(self, type_code: str | None) -> str | None:
        """Return what an ICAO type code stands for, as far as we know it."""
        if type_code is None:
            return None
        return self.models.get(type_code.strip().upper())


def designator_of(callsign: str | None) -> str | None:
    """Return the airline designator a callsign opens with, if it is one.

    A flight number is an airline designator followed by the number of the
    flight, as in KLM1234. Anything else that reaches us here is not one: a
    business jet and most general aviation fly under their registration, and
    the military under a name of its own. Reading the first three letters of
    those would turn PHABC into whatever PHA happens to be, so a callsign that
    is not shaped like a flight number has no designator to give.

    The table is not consulted, deliberately. This is what the aircraft itself
    broadcast, and an airline the table has never heard of still has a code
    worth passing on: it is what a dashboard looks a logo up by.
    """
    if callsign is None:
        return None
    text = callsign.strip().upper()
    if len(text) <= _DESIGNATOR_LENGTH:
        return None
    designator, rest = text[:_DESIGNATOR_LENGTH], text[_DESIGNATOR_LENGTH:]
    if not (designator.isascii() and designator.isalpha() and rest[0].isdigit()):
        return None
    return designator


EMPTY: Final = ReferenceTables()

_tables: ReferenceTables | None = None


def _read(filename: str, key: str) -> dict[str, str]:
    """Read one generated table, tolerating a file that is not there."""
    try:
        payload: Any = json.loads((_DIRECTORY / filename).read_text("utf-8"))
        table = payload[key]
    except (OSError, ValueError, KeyError, TypeError) as err:
        # Nothing here is worth failing a setup over. Without the table the
        # aircraft keep every figure they had; they lose a name.
        _LOGGER.warning("Could not read %s: %s", filename, err)
        return {}
    if not isinstance(table, dict):
        _LOGGER.warning("%s does not hold a table of %s", filename, key)
        return {}
    return {str(code): str(name) for code, name in table.items()}


def _load() -> ReferenceTables:
    """Read both tables. Blocking, so this belongs in the executor."""
    return ReferenceTables(
        airlines=_read(AIRLINES_FILE, "airlines"),
        models=_read(MODELS_FILE, "models"),
    )


async def async_load_reference(hass: HomeAssistant) -> ReferenceTables:
    """Return the tables, reading them off disk the first time they are asked for."""
    global _tables
    if _tables is None:
        _tables = await hass.async_add_executor_job(_load)
        _LOGGER.debug(
            "Loaded %s airlines and %s aircraft types",
            len(_tables.airlines),
            len(_tables.models),
        )
    return _tables
